### ISSUE TITLE
Can't resolve './ID'

### ISSUE THREAD

**Issue by Hyperkid123** [ManageIQ/topological_inventory-api#123]
When trying to build API client from generated code i get following error:

```
ERROR in ./src/model/IDReadOnly.js
Module not found: Error: Can't resolve './ID' in '/home/mmarosi/service-portal/topological_inventory-api-jsclient-1/src/model'
 @ ./src/model/IDReadOnly.js 20:0-22 39:4-6 65:8-10 66:8-10
 @ ./src/model/Authentication.js
 @ ./src/index.js
error Command failed with exit code 2.
```

I am using API code gen and latest v0.1.0 schema. When i check the generated source code there is truly no `ID.js` file. Last successful client generation was from https://github.com/ManageIQ/topological_inventory-api-jsclient/commit/e61a221537fdade2fb3f7270e4b10091d910a371 (Feb 6).

When i was going through the API commits i think this might have something to do with it: https://github.com/ManageIQ/topological_inventory-api/commit/35196a77c7d4881c2a3e5b998b172cab7f832536

cc @carbonin @bdunne

**Comment by martinpovolny** [comment]
In the previous iteration I was fixing this by removing any references to the ID from the generated javascripts. But that was with the previous generator (swagger, not openAPI).

**Comment by Hyperkid123** [comment]
It did work with the OpenAPI a week. On version 0.1

**Comment by bdunne** [comment]
@Hyperkid123 If you rename `parameters/ID` to something else, does that work for you?

The validator says there's nothing wrong with the documents on master...
```
$ swagger-cli validate public/doc/swagger-2-v0.1.0.yaml 
public/doc/swagger-2-v0.1.0.yaml is valid

$ swagger-cli validate public/doc/swagger-2-v0.0.1.yaml 
public/doc/swagger-2-v0.0.1.yaml is valid
```

**Comment by Hyperkid123** [comment]
@bdunne so if u rename `parameters/ID` anywhere in the yam i get an error

```
Error resolving $ref pointer "/home/mmarosi/service-portal/topological_inventory-api/public/doc/swagger-2-v0.1.0.yaml#/parameters/FOO". 
Token "FOO" does not exist.
```

Otherwise its valid. Or do you have something else in mind?

**Comment by bdunne** [comment]
> so if i rename `parameters/ID` anywhere in the yam i get an error

I meant rename all references in the YAML from `parameters/ID` to `parameters/Foo`

**Comment by Hyperkid123** [comment]
> I meant rename all references in the YAML from `parameters/ID` to `parameters/Foo`

If i rename all i get the same error as above

**Comment by martinpovolny** [comment]
@bdunne : Here's a fix to the same issue in the "Service Portal API" repository: https://github.com/ManageIQ/service_portal-api/pull/124

**Comment by bdunne** [comment]
@martinpovolny Looking at the [diff](https://github.com/ManageIQ/service_portal-api/pull/124/files?utf8=%E2%9C%93&diff=unified&w=1), it looks they had an incorrect reference that was fixed.  I don't see any change that would apply to our swagger file.

**Comment by martinpovolny** [comment]
@bdunne : proposed fix here -- https://github.com/ManageIQ/topological_inventory-api/pull/139
