### ISSUE TITLE
Paging links for pagination

### ISSUE THREAD

**Issue by Hyperkid123** [ManageIQ/topological_inventory-api#125]
Collections responses return correctly return links next, prev, first and last page. But those links are pointing towards something like this:
```
https://api-gateway-ci.5a9f.insights-dev.openshiftapps.com/r/insights/platform/topological-inventory/v0.1/sources/4/service_offerings?archived_at=&offset=0
``` 

That is not our API and we obviously don't have access to it. Yes i can compute the query params but i don't think that is something we want do in UI. We either get the part of after the API version (because we have our own base path which also defines API version ) or after `/r` or a object with query params (limit, offset, etc.).

We definitely don't want scheme or host address to be included in the pagination links, because it should be called through client APIs

cc @carbonin @bdunne

**Comment by carbonin** [comment]
I think this is probably an issue with the proxy in front of our service. We were instructed to return only the path for redirections so that must be getting added on after we send our response.

cc @abellotti @coderbydesign any ideas on this one?

**Comment by bdunne** [comment]
For the pagination links we are returning full URLs, I will change that to only the path.

**Comment by bdunne** [comment]
Fixed by: https://github.com/ManageIQ/manageiq-api-common/pull/33
