### ISSUE TITLE
Set DATABASE_URL for all login shell sessions

### ISSUE THREAD

**Issue by carbonin** [ManageIQ/topological_inventory-api#44]
Right now DATABASE_URL is only set in the entrypoint script.

This means that when you shell into a container to use the rails console you need to manually set the env variable to access anything.

We should move this to somewhere where it can be sourced from both situations.

**Comment by Fryguy** [comment]
However this gets fixed I need to replicate to the other microservices.

**Comment by carbonin** [comment]
Fixed by https://github.com/ManageIQ/topological_inventory-api/pull/71 and https://github.com/ManageIQ/topological_inventory-deploy/pull/22
